In [6]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df1 = pd.read_csv("E:/dasein_py/Data Analysis/招商银行/cleaned_features_v3.csv", index_col = 0, header =0)
df2 = pd.read_csv("E:/dasein_py/Data Analysis/招商银行/cleaned_test_v3.csv", index_col = 0, header =0)
lbl = pd.read_csv("E:/dasein_py/Data Analysis/招商银行/cleaned_labels_v3.csv", index_col = 0, header =0)

In [7]:
df1.head()

AGN_CNT_RCT_12_MON  ICO_CUR_MON_ACM_TRX_TM  NB_RCT_3_MON_LGN_TMS_AGV  \
0              2472.0                    72.0                     425.3   
1              2282.0                   222.0                     175.3   
2              2472.0                     2.0                     175.3   
3              2472.0                    92.0                      22.0   
4              2472.0                    92.0                     175.3   

   AGN_CUR_YEAR_AMT  AGN_CUR_YEAR_WAG_AMT  AGN_AGR_LATEST_AGN_AMT  \
0        12015888.3             8816593.9                674873.7   
1        11776572.4             8816593.9               1964626.4   
2        12015888.3             8816593.9               4599822.3   
3        12015888.3             8816593.9                674873.7   
4        12015888.3             8816593.9                674873.7   

   ICO_CUR_MON_ACM_TRX_AMT  COUNTER_CUR_YEAR_CNT_AMT  \
0               25879985.3                       2.0   
1               14755499.8                       2.0   
2                      2.0                       2.0   
3                9622952.0                       2.0   
4                9622952.0                       2.0   

   PUB_TO_PRV_TRX_AMT_CUR_YEAR  MON_12_EXT_SAM_TRSF_IN_AMT  ...  \
0                     660732.0                 262372474.2  ...   
1                     126608.3                         2.0  ...   
2                          2.0                         2.0  ...   
3                          2.0                         2.0  ...   
4                       2802.0                         2.0  ...   

   WTHR_OPN_ONL_ICO  EMP_NBR       REG_CPT  SHH_BCK  HLD_DMS_CCY_ACT_NBR  \
0                 0      2.0  1.200000e+09        0                 12.0   
1                 0   1002.0  5.000002e+06        0                 22.0   
2                 0      2.0  1.000000e+08        1                 12.0   
3                 1      2.0  5.000020e+05        2                 12.0   
4                 1      2.0  1.000000e+08        1                 12.0   

    REG_DT  LGP_HLD_CARD_LVL   OPN_TM  NB_CTC_HLD_IDV_AIO_CARD_SITU  \
0  1708.45                 0   416.84                             0   
1   199.42                 1   195.87                             1   
2  1135.55                 1  1122.00                            -1   
3    98.45                -1    92.00                             2   
4   702.97                -1   355.87                             2   

   HLD_FGN_CCY_ACT_NBR  
0                  2.0  
1                  2.0  
2                  2.0  
3                  2.0  
4                  2.0  

[5 rows x 48 columns]

In [8]:
df2.head()

AGN_CNT_RCT_12_MON  ICO_CUR_MON_ACM_TRX_TM  NB_RCT_3_MON_LGN_TMS_AGV  \
0             23662.0                    92.0                     172.0   
1              2492.0                     2.0                     172.0   
2              1672.0                     2.0                      48.7   
3              5432.0                   102.0                      88.7   
4             11842.0                   782.0                    1545.3   

   AGN_CUR_YEAR_AMT  AGN_CUR_YEAR_WAG_AMT  AGN_AGR_LATEST_AGN_AMT  \
0        11812311.6             8745226.1                135692.0   
1        11812311.6             8745226.1                703149.6   
2          992125.6             8745226.1                992125.6   
3        46729796.3            46729796.3               7356752.4   
4        27085791.9             8745226.1                135002.0   

   ICO_CUR_MON_ACM_TRX_AMT  COUNTER_CUR_YEAR_CNT_AMT  \
0                9444134.2                       2.0   
1                      2.0                       2.0   
2                      2.0                       2.0   
3                8048976.0                       2.0   
4               81516420.9                       2.0   

   PUB_TO_PRV_TRX_AMT_CUR_YEAR  MON_12_EXT_SAM_TRSF_IN_AMT  ...  \
0                          2.0                 594825002.0  ...   
1                          2.0                         2.0  ...   
2                          2.0                         2.0  ...   
3                    2154106.4                         2.0  ...   
4                    2421499.6                         2.0  ...   

   WTHR_OPN_ONL_ICO  EMP_NBR       REG_CPT  SHH_BCK  HLD_DMS_CCY_ACT_NBR  \
0                 0  26622.0  1.000000e+08        0                 12.0   
1                 0   1502.0  3.800000e+08        1                 12.0   
2                 1      2.0  1.000000e+08        0                 42.0   
3                 0    432.0  5.000002e+06        2                 12.0   
4                 0    902.0  1.131689e+09        1                 12.0   

      REG_DT  LGP_HLD_CARD_LVL   OPN_TM  NB_CTC_HLD_IDV_AIO_CARD_SITU  \
0  242461.35                 0  1588.13                             0   
1     432.00                 0    82.65                             0   
2     705.23                -1   512.65                             1   
3     442.00                 1   432.00                             1   
4    3747.48                -1  3200.06                             1   

   HLD_FGN_CCY_ACT_NBR  
0                  2.0  
1                  2.0  
2                 22.0  
3                  2.0  
4                  2.0  

[5 rows x 48 columns]

In [13]:
label = lbl.values

In [11]:
from xgboost.sklearn import XGBClassifier
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(copy=False)
df2_features = scaler.fit_transform(df2)
df1_features = scaler.fit_transform(df1)

In [12]:
df1_features, df2_features

(array([[-0.01771666, -0.04036806,  0.13334904, ..., -0.42572884,
         -1.18894007, -0.23009299],
        [-0.01797979, -0.02722852, -0.20762554, ..., -0.79782908,
         -0.56876373, -0.23009299],
        [-0.01771666, -0.04649984, -0.20762554, ...,  0.76171837,
         -1.80911642, -0.23009299],
        ...,
        [ 0.00867952,  0.05248468, -0.20762554, ...,  2.46359244,
         -1.80911642, -0.23009299],
        [-0.01771666, -0.04562387, -0.27118321, ..., -0.26875194,
         -1.18894007, -0.23009299],
        [-0.01771666, -0.04387193, -0.12579164, ...,  0.63298115,
          2.532118  , -0.23009299]]),
 array([[ 0.10232026, -0.12387589, -0.29241471, ...,  1.56024628,
         -1.1976317 , -0.16766289],
        [-0.06773752, -0.15788593, -0.29241471, ..., -0.98796441,
         -1.1976317 , -0.16766289],
        [-0.07432455, -0.15788593, -0.53567716, ..., -0.26013634,
         -0.53231156,  1.2934516 ],
        ...,
        [-0.0817952 , -0.08608696, -0.02271498, ..., -

In [15]:
from sklearn.model_selection import train_test_split #数据集训练集划分
x_train,x_test,y_train,y_test=train_test_split(df1_features,label,test_size=.2,random_state=22)
x_train

array([[-0.01771666, -0.04212   , -0.37129334, ...,  0.40428524,
        -0.56876373, -0.23009299],
       [-0.00688675, -0.0193448 ,  0.16976512, ...,  0.08433662,
         0.05141262,  0.94220602],
       [-0.02094347, -0.03511224, -0.13479337, ...,  2.10181475,
         1.29176531, -0.23009299],
       ...,
       [-0.02023717, -0.04124403, -0.18034758, ..., -0.90809348,
         1.29176531, -0.23009299],
       [-0.01771666, -0.04649984, -0.42121202, ..., -1.03955869,
         1.29176531, -0.23009299],
       [-0.01771666, -0.03861612, -0.41671116, ..., -0.07861826,
         1.29176531, -0.23009299]])

In [20]:
y_train.reshape(-1)

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [17]:
from pytorch_tabnet.tab_model import TabNetClassifier, TabNetRegressor
from pytorch_tabnet.pretraining import TabNetPretrainer
import torch

In [70]:
# TabNetPretrainer 预训练模型
unsupervised_model = TabNetPretrainer(
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    mask_type='sparsemax' # "sparsemax"
)

unsupervised_model.fit(
    X_train=x_train,
    eval_set=[df1.values],
    pretraining_ratio=0.8,
)

clf = TabNetClassifier(
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    scheduler_params={"step_size":10, # how to use learning rate scheduler
                      "gamma":0.9},
    scheduler_fn=torch.optim.lr_scheduler.StepLR,
    mask_type='sparsemax' # This will be overwritten if using pretrain model
)

clf.fit(x_train, y_train.reshape(-1),
    eval_set= [(x_train, y_train.reshape(-1)), (df1.values, lbl.values.reshape(-1))],
    eval_name=['train', 'valid'],
    eval_metric=['auc'],
    from_unsupervised=unsupervised_model
)

Device used : cpu
epoch 0  | loss: 655.35333| val_0_unsup_loss: 5.044311298413062e+19|  0:00:02s
epoch 1  | loss: 17.48018| val_0_unsup_loss: 1.006651213611008e+16|  0:00:05s
epoch 2  | loss: 1.84422 | val_0_unsup_loss: 2.5346904116166656e+16|  0:00:08s
epoch 3  | loss: 1.06343 | val_0_unsup_loss: 1.789790181654528e+17|  0:00:11s
epoch 4  | loss: 1.0783  | val_0_unsup_loss: 2.806378661098291e+16|  0:00:13s
epoch 5  | loss: 1.04342 | val_0_unsup_loss: 5.267322551507354e+16|  0:00:16s
epoch 6  | loss: 1.03608 | val_0_unsup_loss: 1040009150857216.0|  0:00:19s
epoch 7  | loss: 1.03378 | val_0_unsup_loss: 6721049366364160.0|  0:00:22s
epoch 8  | loss: 1.04402 | val_0_unsup_loss: 2.9546870308991926e+19|  0:00:25s
epoch 9  | loss: 1.0561  | val_0_unsup_loss: 5.157704592292577e+18|  0:00:27s
epoch 10 | loss: 1.03691 | val_0_unsup_loss: 3.6109418709070643e+18|  0:00:30s
epoch 11 | loss: 1.03819 | val_0_unsup_loss: 1.4984565576284766e+19|  0:00:33s
epoch 12 | loss: 1.03456 | val_0_unsup_loss: 2.

In [71]:
predict_proba = clf.predict_proba(x_test)
predict_proba[:,0]

array([0.96832305, 0.9685319 , 0.94283664, ..., 0.950373  , 0.97888523,
       0.97209686], dtype=float32)

In [72]:
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test.reshape(-1), predict_proba[:,1])
auc(false_positive_rate, true_positive_rate)

0.6511318268787747

In [73]:
predict_proba2 = clf.predict_proba(x_test)
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test.reshape(-1), predict_proba2[:,1])
auc(false_positive_rate, true_positive_rate)

0.6511318268787747

In [75]:
y_pred = clf.predict(x_test)
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85      5914
           1       0.00      0.00      0.00      2086

    accuracy                           0.74      8000
   macro avg       0.37      0.50      0.43      8000
weighted avg       0.55      0.74      0.63      8000



D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [47]:
from sklearn.decomposition import PCA

In [48]:
pca = PCA(n_components=15)

In [55]:
x_train2 = pca.fit_transform(df1)

In [56]:
x_train2

array([[-2.43485860e+09, -9.79041901e+08,  3.53320372e+08, ...,
         1.69800686e+07, -2.25714355e+07, -4.64186443e+06],
       [-2.60326552e+09, -1.20454133e+09,  8.68250383e+08, ...,
        -1.52891318e+07,  2.49463735e+07, -4.31176019e+06],
       [-2.68028228e+09, -1.20485478e+09,  8.54260903e+08, ...,
        -6.92020453e+06,  1.85919676e+06, -6.11148416e+06],
       ...,
       [-1.83277407e+09,  1.97828903e+08, -1.41091945e+09, ...,
        -2.56263370e+07,  1.64018130e+07,  1.97540606e+07],
       [-2.69602533e+09, -1.20535081e+09,  8.69142156e+08, ...,
        -7.76629505e+06,  3.55282768e+06, -5.94794662e+06],
       [-2.49502542e+09, -6.73593810e+08, -1.75264765e+08, ...,
         2.45673520e+07, -3.89305184e+07,  6.36896835e+06]])

In [57]:
features2 = scaler.fit_transform(x_train2)
features2

array([[-0.01340227, -0.01963732,  0.01192276, ...,  0.04434032,
        -0.07542411, -0.01812773],
       [-0.01432923, -0.02416032,  0.02929903, ..., -0.03992475,
         0.08336014, -0.01683858],
       [-0.01475316, -0.0241666 ,  0.02882695, ..., -0.01807084,
         0.00621264, -0.02386699],
       ...,
       [-0.01008819,  0.00396799, -0.04761134, ..., -0.06691846,
         0.05480787,  0.07714491],
       [-0.01483982, -0.02417655,  0.02932912, ..., -0.02028025,
         0.01187204, -0.02322833],
       [-0.01373345, -0.01351074, -0.00591429, ...,  0.06415312,
        -0.1300892 ,  0.02487253]])

In [58]:
x_train2,x_test2,y_train2,y_test2 =train_test_split(features2,label,test_size=.2,random_state=22)

In [60]:
label

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [76]:
# 调参
# TabNetPretrainer 预训练模型
unsupervised_model = TabNetPretrainer(
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-5),
    mask_type='sparsemax' # "sparsemax"
)

unsupervised_model.fit(
    X_train=x_train2,
    eval_set=[features2],
    pretraining_ratio=0.8,
)

clf2 = TabNetClassifier(
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-5),
    scheduler_params={"step_size":10, # how to use learning rate scheduler
                      "gamma":0.9},
    scheduler_fn=torch.optim.lr_scheduler.StepLR,
    mask_type='sparsemax' # This will be overwritten if using pretrain model
)

clf2.fit(x_train2, y_train2.reshape(-1),
    eval_set= [(x_train2, y_train2.reshape(-1)), (features2, lbl.values.reshape(-1))],
    eval_name=['train', 'valid'],
    eval_metric=['auc'],
    from_unsupervised=unsupervised_model
)

Device used : cpu
epoch 0  | loss: 520.54109| val_0_unsup_loss: 1.40954 |  0:00:02s
epoch 1  | loss: 611.17195| val_0_unsup_loss: 1.87714 |  0:00:04s
epoch 2  | loss: 411.79755| val_0_unsup_loss: 1.9529  |  0:00:06s
epoch 3  | loss: 371.55147| val_0_unsup_loss: 2.14971 |  0:00:08s
epoch 4  | loss: 296.11923| val_0_unsup_loss: 1.8425  |  0:00:10s
epoch 5  | loss: 411.97911| val_0_unsup_loss: 2.48366 |  0:00:12s
epoch 6  | loss: 417.03189| val_0_unsup_loss: 2.99035 |  0:00:14s
epoch 7  | loss: 372.76401| val_0_unsup_loss: 2.71654 |  0:00:16s
epoch 8  | loss: 385.54724| val_0_unsup_loss: 3.37694 |  0:00:18s
epoch 9  | loss: 469.75974| val_0_unsup_loss: 2.40193 |  0:00:20s
epoch 10 | loss: 314.84748| val_0_unsup_loss: 3.56644 |  0:00:22s

Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_unsup_loss = 1.40954
Best weights from best epoch are automatically used!
Device used : cpu
Loading weights from unsupervised pretraining
epoch 0  | loss: 0.78046 | train_auc: 0.4932  

In [77]:
from sklearn.metrics import classification_report

In [80]:
y_pred2 = clf2.predict(x_test2)
print(classification_report(y_test2.reshape(-1), y_pred2))

              precision    recall  f1-score   support

           0       0.90      0.06      0.11      5914
           1       0.27      0.98      0.42      2086

    accuracy                           0.30      8000
   macro avg       0.58      0.52      0.27      8000
weighted avg       0.73      0.30      0.19      8000



In [83]:
predict_proba3 = clf2.predict_proba(x_test2)
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test2.reshape(-1), predict_proba3[:,1])
auc(false_positive_rate, true_positive_rate)

0.5801404503216607

### AutoGluon

In [105]:
from autogluon.tabular import TabularPredictor
import pandas as pd

In [113]:
train_data = pd.read_csv('E:/dasein_py/Data Analysis/招商银行/train.csv')
save_path = 'E:/dasein_py/Data Analysis/招商银行/agModels-predictClass/'
predictor = TabularPredictor(label= 'LABEL' , eval_metric='roc_auc', path = save_path).fit(train_data)

TypeError: import_optional_dependency() got an unexpected keyword argument 'errors'

In [89]:
lbl

LABEL
0          0
1          0
2          0
3          1
4          1
...      ...
39995      0
39996      0
39997      0
39998      1
39999      0

[40000 rows x 1 columns]

In [109]:
train_data

LABEL AGN_CNT_RCT_12_MON ICO_CUR_MON_ACM_TRX_TM  \
0          0                  ?                     72   
1          0               2282                    222   
2          0                  ?                      2   
3          1                  ?                      ?   
4          1                  ?                      ?   
...      ...                ...                    ...   
39995      0                  ?                      2   
39996      0                  ?                     72   
39997      0              21532                   1132   
39998      1                  ?                     12   
39999      0                  ?                     32   

      NB_RCT_3_MON_LGN_TMS_AGV AGN_CUR_YEAR_AMT AGN_CUR_YEAR_WAG_AMT  \
0                        425.3                ?                    ?   
1                            ?       11776572.4                    ?   
2                            ?                ?                    ?   
3                           22                ?                    ?   
4                            ?                ?                    ?   
...                        ...              ...                  ...   
39995                     55.3                ?                    ?   
39996                    145.3                ?                    ?   
39997                        ?       81027170.3                    ?   
39998                    128.7                ?                    ?   
39999                    235.3                ?                    ?   

      AGN_AGR_LATEST_AGN_AMT ICO_CUR_MON_ACM_TRX_AMT COUNTER_CUR_YEAR_CNT_AMT  \
0                          ?              25879985.3                        2   
1                  1964626.4              14755499.8                        2   
2                  4599822.3                       2                        2   
3                          ?                       ?                        2   
4                          ?                       ?                        ?   
...                      ...                     ...                      ...   
39995                      ?                       2                        2   
39996                      ?              16431457.9                        2   
39997             12772212.7             596254539.9                        2   
39998                      ?                  488502                        2   
39999                      ?                 2740802                        2   

      PUB_TO_PRV_TRX_AMT_CUR_YEAR  ... WTHR_OPN_ONL_ICO EMP_NBR     REG_CPT  \
0                          660732  ...                B       2  1200000002   
1                        126608.3  ...                B    1002     5000002   
2                               2  ...                B       2           ?   
3                               2  ...                A       2      500002   
4                               ?  ...                A       2           ?   
...                           ...  ...              ...     ...         ...   
39995                           2  ...                B     402   300000002   
39996                           2  ...                B       2   500000002   
39997                    484869.1  ...                B    5002   500000002   
39998                           2  ...                B       2    10000002   
39999                           2  ...                B    2002  1007800002   

      SHH_BCK HLD_DMS_CCY_ACT_NBR   REG_DT LGP_HLD_CARD_LVL   OPN_TM  \
0          32                  12  1708.45                ?   416.84   
1          32                  22   199.42                F   195.87   
2           2                  12  1135.55                F     1122   
3          12                  12    98.45              NaN       92   
4           2                  12        ?              NaN   355.87   
...       ...                 ...      ...              ...      ...   
39995      12      